{
  "formatVersion": "1.1",
  "component": {
    "group": "com.catering",
    "module": "commons",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "commons-1.0-plain.jar",
          "url": "commons-1.0-plain.jar",
          "size": 9273,
          "sha512": "13fa8896acd329880ee40f386ac41433a5c8680140ff3b0edcba7f17156a1f27fbe27fce1af874710363607cea6f2829776360f00d114c9fa14c86c0e187ec45",
          "sha256": "f2c3dfb0cd04a22eeb9a7e1b963d73d55d81b1e1a39dcc623c43450ec59bd852",
          "sha1": "952eaf11491d534fbd760ae173bb07fa2abe9d7f",
          "md5": "6f67c84b4d36cc5659572fd18115ddb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.22"
          }
        }
      ],
      "files": [
        {
          "name": "commons-1.0-plain.jar",
          "url": "commons-1.0-plain.jar",
          "size": 9273,
          "sha512": "13fa8896acd329880ee40f386ac41433a5c8680140ff3b0edcba7f17156a1f27fbe27fce1af874710363607cea6f2829776360f00d114c9fa14c86c0e187ec45",
          "sha256": "f2c3dfb0cd04a22eeb9a7e1b963d73d55d81b1e1a39dcc623c43450ec59bd852",
          "sha1": "952eaf11491d534fbd760ae173bb07fa2abe9d7f",
          "md5": "6f67c84b4d36cc5659572fd18115ddb6"
        }
      ]
    }
  ]
}
