{
  "formatVersion": "1.1",
  "component": {
    "group": "com.catering",
    "module": "Commons",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Commons-0.0.1-SNAPSHOT-plain.jar",
          "url": "Commons-0.0.1-SNAPSHOT-plain.jar",
          "size": 9273,
          "sha512": "0b2a55e94675138df3359f03f1b3e26295438a4684a406362c683e6090af7a71cb745efdd9e42b73ba78586224024aaef69a5b12e1c7300e10578a3cd5cbcae1",
          "sha256": "af63b2c2abfff246adab256a2803d47dbb21d3b931aed6529742d34d26e94c10",
          "sha1": "970174e2fe4b30b8432e4ac05716150cc2e7db5d",
          "md5": "9ad65b7846ec14825ae501bca4092953"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.22"
          }
        }
      ],
      "files": [
        {
          "name": "Commons-0.0.1-SNAPSHOT-plain.jar",
          "url": "Commons-0.0.1-SNAPSHOT-plain.jar",
          "size": 9273,
          "sha512": "0b2a55e94675138df3359f03f1b3e26295438a4684a406362c683e6090af7a71cb745efdd9e42b73ba78586224024aaef69a5b12e1c7300e10578a3cd5cbcae1",
          "sha256": "af63b2c2abfff246adab256a2803d47dbb21d3b931aed6529742d34d26e94c10",
          "sha1": "970174e2fe4b30b8432e4ac05716150cc2e7db5d",
          "md5": "9ad65b7846ec14825ae501bca4092953"
        }
      ]
    }
  ]
}
